---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres 
  labels:
    app: postgres 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres 
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      containers:
      - name: postgres 
        image: postgres 
        livenessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-d", "boundary", "-c", "SELECT", "1"]
        ports:
        - containerPort: 5432 
        env:
        - name: POSTGRES_DB 
          value: "boundary"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres 
  ports:
    - port: 5432 
      targetPort: 5432 
